[package]
edition = "2021"
name = "rs-chinese-chess"
version = "0.1.0"

[dependencies]
anyhow = "1.0.71"
fltk = { version = "1.4.6", features = ["fltk-bundled"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

#- `opt-level = "z"`：将优化级别设置为最小化，这将减小生成的二进制文件的大小。
#- `lto = true`：启用链接时优化（Link Time Optimization）以进一步减小生成的二进制文件的大小。
#- `codegen-units = 1`：将代码生成单元设置为1，这将减少生成的目标文件的数量，从而减小最终生成的二进制文件的大小。
#- `panic = "abort"`：将 panic 的处理方式设置为终止程序，这将减小运行时库的大小。
